### ISSUE TITLE
Miette integration seems not to be completed and other understandable behaviors

### ISSUE THREAD

**Issue by corebreaker** [olson-sean-k/wax#32]
With Cargo file like this:
```toml
[package]
name = "wax-proto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miette = { version = "5.3.0", features = ["fancy"] }
wax = { version = "0.5.0", features = ["diagnostics", "diagnostics-report", "miette"] }
```

Note that, the Cargo file can be like this too, the problem will be the same:
```toml
[package]
name = "wax-proto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miette = { version = "5.3.0", features = ["fancy"] }
wax = { version = "0.5.0", features = ["diagnostics"] }
```

With the file, `main.rs`:
```rust
use miette::Result;
use wax::Glob;

fn main() -> Result<()> {
    Glob::new("**//*.txt")?;
    Ok(())
}
```

When we run the command `cargo run`:
![image](https://user-images.githubusercontent.com/9797898/189055147-925677f4-108b-4ba9-a849-9f2edca3fec1.png)

I found this result a little odd. With activated features in `Cargo.toml`, and https://github.com/olson-sean-k/wax/blob/master/src/lib.rs#L401, the response is understandable.

And that, even if we add the `Diagnostic` trait:
```rust
use miette::Diagnostic;
use miette::Result;
use wax::Glob;

fn main() -> Result<()> {
    Glob::new("**//*.txt")?;
    Ok(())
}
```

Plus, with that version of `main.rs`:
```rust
use miette::Diagnostic;
use wax::{Glob, GlobError};

fn main() -> Result<(), GlobError<'static>> {
    Glob::new("**//*.txt")?;
    Ok(())
}
```

We have this response:
![image](https://user-images.githubusercontent.com/9797898/189058111-4de1d001-1973-4787-89ad-991b30cbe7bb.png)

We don't have the expected fancy printing from Miette.

We can notice that in the Cargo.toml of Wax, here: https://github.com/olson-sean-k/wax/blob/master/Cargo.toml#L42, the `fancy` feature is not activated. Is it normal ?

To have a good use of the integration of Miette, there is something missing in our prototype project ?

**Comment by olson-sean-k** [comment]
I'm guessing the issue here concerns versioning and incompatible traits: version `0.5.0` of `wax` (the most recent published version at time of writing) [integrates with `miette` version `^4.7.0`](https://github.com/olson-sean-k/wax/blob/8dba2780fedd76b758af73e53aa22d82d85db466/Cargo.toml#L52). The example manifests that you've shared specify a dependency on version `5.3.0` of `miette`, so the traits are **not** compatible. You'll need to downgrade to a version specification of `^4.7.0` for `miette` if you're using version `0.5.0` of `wax`.

See also [this comment on a related `miette` issue](https://github.com/zkat/miette/issues/25#issuecomment-1185020781).

**Comment by corebreaker** [comment]
Hello, i knew this issue, but downgrade Miette doesn't fix the problem, you can check it by yourself.

**Comment by olson-sean-k** [comment]
> I knew this issue, but downgrade Miette doesn't fix the problem, you can check it by yourself.

Hmm, that doesn't seem right. For what it's worth, **I expect none of the example manifests you've shared so far to work properly with `miette`**. Also note that while the `master` branch of `wax` now uses a `miette` feature for this, version `0.5.0` does **not** and only the `diagnostics*` features should be used with that version.

I have some working code that uses this integration, **but I also created a quick example just now and it works as expected**. Are you sure you've taken an appropriate dependency specification on `miette`?

Here's a fairly minimal working manifest.

```toml
[package]
name = "wax_issue_32"
version = "0.0.0"
edition = "2021"

[dependencies]

[dependencies.miette]
version = "^4.7.0"
features = ["fancy"]

[dependencies.wax]
version = "^0.5.0"
features = ["diagnostics"]
```

I tested this with the following code and it prints diagnostics using `miette`'s fancy reporter.

```rust
use wax::Glob;

fn main() -> miette::Result<()> {
    let _glob = Glob::new("**/{foo,**/bar}")?; // Error!
    Ok(())
}
```
